services:
  api:
    image: adenilsonkon/api-python-medical:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST: 0.0.0.0
      PORT: 8443
      SSL_CERTFILE: /tls/tls.crt
      SSL_KEYFILE: /tls/tls.key
    ports:
      - "8443:8443"
    volumes:
      - ./certs:/tls:ro
